version: 2.1
orbs:
  terraform: circleci/terraform@2.1.0
jobs:
  Create and validate ACM certificate:
    executor: terraform/default
    working_directory: ~
    steps:
      - checkout:
          path: ~
      - terraform/plan:
          path: terraform/acm/
          backend_config: "bucket=${TERRAFORM_STATE_BUCKET},key=website/acm,region=${AWS_REGION}"
          workspace: ""
          var: domain_name=${WEBSITE}
      - terraform/apply:
          path: terraform/acm/
          backend_config: "bucket=${TERRAFORM_STATE_BUCKET},key=website/acm,region=${AWS_REGION}"
          workspace: ""
          var: domain_name=${WEBSITE}
  Create main website:
    executor: terraform/default
    working_directory: ~
    steps:
      - checkout:
          path: ~
      - terraform/plan:
          path: terraform/website/
          backend_config: "bucket=${TERRAFORM_STATE_BUCKET},key=website/website,region=${AWS_REGION}"
          var: domain_name=${WEBSITE},email_address=${EMAIL}
      - terraform/apply:
          path: terraform/website/
          backend_config: "bucket=${TERRAFORM_STATE_BUCKET},key=website/website,region=${AWS_REGION}"
          var: domain_name=${WEBSITE},email_address=${EMAIL}
workflows:
  version: 2
  Create website:
    jobs:
      - Create and validate ACM certificate:
          context:
            - personal
            - AWS
      - Create main website:
          context:
            - personal
            - AWS
          requires: 
            - Create and validate ACM certificate
